### ISSUE TITLE
[BUG] Error while adding the stale label

### ISSUE THREAD

**Issue by C0ZEN** [Sonia-corporation/stale#167]
**Describe the bug**
Error: [#26] Could not fetch the label stale
  [#26] Found the label stale
  Error: [#26] Could not find the stale label stale
  Error: [Error] Could not find the stale label stale
  ##[debug]Error: Could not find the stale label stale
  ##[debug]    at IssueStaleProcessor.<anonymous> (/home/runner/work/stale/stale/dist/index.js:30:35387)
  ##[debug]    at Generator.next (<anonymous>)
  ##[debug]    at fulfilled (/home/runner/work/stale/stale/dist/index.js:30:2285)
  ##[debug]    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  Error: Stale action failed with error Could not find the stale label stale
  ##[debug]Node Action run completed with exit code 1
  ##[debug]Finishing: Stale

**Additional context**
[Add any other context about the problem here.](https://github.com/Sonia-corporation/stale/runs/4449863627?check_suite_focus=true)

**Comment by C0ZEN** [comment]
Used https://docs.github.com/en/graphql/overview/explorer, and I just figured out that I didn't configure yet the stale label on this repository…
I added a debug log and that should be enough. 😉
